### ISSUE TITLE
Feature request: make disambiguators opt-in

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#15]
I changed my mind after #13 😆 I liked the way the links looked before, I'd rather change them by hand than have `type@` everywhere. Sorry to be a pain!

**Comment by poliorcetics** [comment]
No problems !

I won't have much time until Saturday to do it, but I'll try to add it this week-end.

I want to write better tests before adding any more features though, right now the tests don't cover everything properly and I'm always afraid to miss things.

**Comment by poliorcetics** [comment]
I'm not yet ready to do this (still writing more tests in the `better-tests` branch) but I'm thinking about it. Here is what I have:

- Always show the item type (if any) at the end of the diff line (`384:   "old line" (item disambiguation: 'type@')`)
- A `--disambiguate` (short `-d`) option that would apply the `type@` automatically (for a first implementation, all of them, on all the given files)
- Always add the `()` and `!` disambiguation since they make the link very clear and do not clutter as much as 'type@' or 'primitve@' do.

What do you think about it ?

**Comment by jyn514** [comment]
I like always applying `()` and `!` very much, as well as making `type@` opt-in. I don't have strong opinions on displaying the disambiguator when the link is converted; I mostly skip over that text anyway 🙃

**Comment by poliorcetics** [comment]
This should work well now and this is tested so (hopefully) it won't break any time soon
