### ISSUE TITLE
`#method.x` choses the wrong `Self`

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#16]
Haven't tried to make an MVCE yet, but if you run `intraconv` on tracing-subscriber, it turns `    /// [`on_exit`]: #method.on_exit` into `SubscriberExt` when it should use `Layer` instead. This is https://github.com/tokio-rs/tracing/blob/e9b6645f0c7cff6e4164b9ecd3d290939ffd77d9/tracing-subscriber/src/layer.rs#L250

**Comment by poliorcetics** [comment]
That means it's missing the `pub trait Layer<S>` declaration.

Its probably because my regex is expecting a space somewhere when there is none, I'll look into it.

**Comment by jyn514** [comment]
It has where bounds, that might be it:

```
pub trait Layer<S>
where
    S: Subscriber,
    Self: 'static,
{
```
Maybe _only_ look for `trait S` without looking for the opening bracket? Otherwise you'll have to use a multiline regex.

**Comment by poliorcetics** [comment]
I just tested on the file, it should be okay now:

<img width="333" alt="Screenshot 2020-10-11 at 01 13 30" src="https://user-images.githubusercontent.com/7951708/95666909-fb8bb300-0b5e-11eb-92eb-8d5e74216659.png">

Edit: to explain what happened: the `pub trait Layer<S>` was correctly detected but `intraconv` detected its end too soon and moved on to the next type it knew; `SubscriberExt`. Since it now ensures to have at least reach the type declaration before ending its associated block, the issue should be completely fixed. I'm currently writing more tests for that.
